name: chess_timer
description: Timer for chess matches.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  circular_countdown_timer: ^0.0.8
  cupertino_icons: ^1.0.1
  flutter_sound_lite: 4.0.6
  wakelock: ^0.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/timer_button.wav
